version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - SERVER_PORT=$SERVER_PORT
      - JWT_SECRET=$JWT_SECRET
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER
    stdin_open: true
    tty: true

volumes: 
  db: